import {
  Box,
  Button,
  Stack,
  Text,
  useColorMode,
  useColorModeValue,
} from "@chakra-ui/react";
import Head from "next/head";
import { MoonIcon, SunIcon } from "@chakra-ui/icons";
import { CustomChakraButton } from "ui";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();
  const bg = useColorModeValue("pink.500", "pink.200");
  const buttonColor = useColorModeValue("purple", "yellow");

  return (
    <div>
      <Head>
        <title>Chakra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto w-auto px-4 mt-10 pb-8 sm:pt-24 lg:px-8">
        <h1 className="mx-auto text-center text-6xl font-extrabold tracking-tight dark:text-white sm:text-7xl lg:text-8xl xl:text-8xl">
          Chakra
        </h1>
        <Stack h="100vh" direction={["column"]} spacing="md">
          <Box>
            <Button onClick={toggleColorMode}>
              {colorMode === "light" ? <MoonIcon /> : <SunIcon color="icon" />}
            </Button>
            <Box
              bg={bg}
              w="100%"
              p={4}
              display="flex"
              alignItems="center"
              justifyContent="space-between"
              mt="4"
              cursor="pointer"
              borderLeft="6px solid"
              borderRadius="5px"
              boxShadow="dark-lg"
            >
              <Text fontSize="24px" fontWeight="bold" mr="1.5rem">
                {colorMode === "light" ? `Light` : "Dark"} Color Mode
              </Text>
              <Button colorScheme={buttonColor}>😀 open</Button>
            </Box>
          </Box>
          <Box>
            <Text fontSize={{ base: "24px", md: "40px", lg: "56px" }}>
              Responisve Button
            </Text>
            <Button w={[200, 400, 500]} colorScheme="orange">
              Big Button
            </Button>
          </Box>
          <Text fontSize="xl">Custom Button</Text>
          <Box>
            <CustomChakraButton title="order" mr="10" />
            <CustomChakraButton title="product" colorScheme="purple" />
          </Box>
          <Text fontSize="xl">Original Button</Text>
          <Stack spacing={4} direction="row" align="center">
            <Button colorScheme="primary">Primary</Button>
            <Button colorScheme="secondary">Secondary</Button>
            <Button colorScheme="danger">Danger</Button>
            <Button colorScheme="warning">Warning</Button>
            <Button colorScheme="success">Success</Button>
            <Button colorScheme="light">Light</Button>
          </Stack>
          <Stack spacing={4} direction="row" align="center">
            <Button colorScheme="primary" size="xs">
              XS
            </Button>
            <Button colorScheme="primary" size="sm">
              SM
            </Button>
            <Button colorScheme="primary" size="md">
              MD
            </Button>
            <Button colorScheme="primary" size="lg">
              LG
            </Button>
          </Stack>
          <Stack spacing={4} direction="row" align="center">
            <Button colorScheme="primary" variant="outline">
              Primary
            </Button>
            <Button colorScheme="secondary" variant="outline">
              Secondary
            </Button>
            <Button colorScheme="danger" variant="outline">
              Danger
            </Button>
            <Button colorScheme="warning" variant="outline">
              Warning
            </Button>
            <Button colorScheme="success" variant="outline">
              Success
            </Button>
            <Button colorScheme="light" variant="outline">
              Light
            </Button>
          </Stack>
        </Stack>
      </main>
    </div>
  );
}
